language: r
cache: packages
sudo: required
dist: trusty
env:
- NOT_CRAN=true
r:
- release
before_install:
  - sudo add-apt-repository ppa:ubuntugis/ppa --yes
  - sudo apt-get --yes --force-yes update -qq
  - sudo apt-get install --yes libudunits2-dev libproj-dev libgeos-dev libgdal-dev
r_packages:
- formatR
- devtools
notifications:
  email:
    on_success: change
    on_failure: change
r_github_packages:
- jimhester/covr
r_check_args: "--no-vignettes"
after_success:
- Rscript -e 'library(covr); coveralls()'

